### PR TITLE
Solved issue #1 - rotation

### PR DESCRIPTION
**Pull request by ZvikaZ**
Added '\fancytabsRotate'.
The default value is '90', it can be changed to '0' to make it regular, or any other value.

I haven't touched the documentation code.

### CODE REVIEW

**Comment by raphink** [comment]
That looks good. Could you document the feature please?

**Comment by ZvikaZ** [comment]
Added documentation.
I have never worked with .dtx files, please verify me...

**Comment by ZvikaZ** [comment]
I've also solved issue #2.
Since I'm not used to .dtx files, I'm attaching the resulting .sty file, just to be sure...

```
%%
%% This is file `fancytabs.sty',
%% generated with the docstrip utility.
%%
%% The original source files were:
%%
%% fancytabs.dtx  (with options: `package')
%% 
%% This is a generated file.
%% 
%% Copyright (C) 2011 by Raphaël Pinson
%% 
%% This file may be distributed and/or modified under the
%% conditions of the LaTeX Project Public License, either
%% version 1.2 of this license or (at your option) any later
%% version. The latest version of this license is in:
%% 
%%    http://www.latex-project.org/lppl.txt
%% 
%% and version 1.2 or later is part of all distributions of
%% LaTeX version 1999/12/01 or later.
%% 
\NeedsTeXFormat{LaTeX2e}[1999/12/01]
\ProvidesPackage{fancytabs}
   [2012/09/17 1.8 Fancy page border tabs with Tikz]

\ProvidesPackage{fancytabs}
\RequirePackage{tikz}

\newcommand{\tab@style}{\Large\scshape}
\newlength{\tab@height}
\setlength{\tab@height}{4cm}
\newlength{\tab@width}
\setlength{\tab@width}{1cm}
\newcommand{\tab@count}{6}
\newcommand{\tab@leftcolor}{white}
\newcommand{\tab@rightcolor}{gray!50}
\newlength{\tab@top}
\setlength{\tab@top}{\the\tab@height}
\newcommand{\tab@textvpos}{0.5}
\newcommand{\tab@texthpos}{\tab@textvpos}
\newlength{\tab@gap}
\setlength{\tab@gap}{0in}
\newcommand{\tab@floor}{0}
\newcommand{\tab@rotate}{90}

\newcommand{\fancytabsStyle}[1]{\renewcommand{\tab@style}{#1}}
\newcommand{\fancytabsHeight}[1]{\setlength{\tab@height}{#1}}
\newcommand{\fancytabsWidth}[1]{\setlength{\tab@width}{#1}}
\newcommand{\fancytabsCount}[1]{\renewcommand{\tab@count}{#1}}
\newcommand{\fancytabsLeftColor}[1]{\renewcommand{\tab@leftcolor}{#1}}
\newcommand{\fancytabsRightColor}[1]{\renewcommand{\tab@rightcolor}{#1}}
\newcommand{\fancytabsTop}[1]{\setlength{\tab@top}{#1}}
\newcommand{\fancytabsTextVPos}[1]{\renewcommand{\tab@textvpos}{#1}}
\newcommand{\fancytabsTextHPos}[1]{\renewcommand{\tab@texthpos}{#1}}
\newcommand{\fancytabsGap}[1]{\setlength{\tab@gap}{#1}}
\newcommand{\fancytabsFloor}[1]{\renewcommand{\tab@floor}{#1}}
\newcommand{\fancytabsRotate}[1]{\renewcommand{\tab@rotate}{#1}}

\AtBeginDocument{\@ifpackageloaded{babel}
  {\@ifundefined{active@char;}{}{%
    \g@addto@macro\tikz@installcommands{%
      \shorthandoff{;}}%
      \g@addto@macro\tikz@uninstallcommands{%
        \shorthandon{;}}%
  }%
  }{}%
}

\newcommand{\fancytab}[3][RIGHT]{%
  \ifstrequal{#1}{LEFT}
    {
      \newcommand{\eastwest}{west}
      \newcommand{\multiplier}{0.5}
    }
    { %else
      \newcommand{\eastwest}{east}
      \newcommand{\multiplier}{-0.5}
    }
  \begin{tikzpicture}[remember picture,overlay]%
    \node[yshift={-1*(\the\tab@top+\the\tab@height/2+
                 mod(#3-1-\tab@floor,\tab@count)*
                 (\the\tab@height+\the\tab@gap))},
                  xshift=\multiplier*\the\tab@width]
      at (current page.north \eastwest) {
      \tikz\shade[shading=axis,bottom color=\tab@leftcolor,
                  top color=\tab@rightcolor,shading angle=-90]
        (0,0) rectangle (\the\tab@width,\the\tab@height)
           node[rotate=0]
                  at (\tab@texthpos*\the\tab@width,\tab@textvpos*\the\tab@height)
                      {\rotatebox{\tab@rotate}{\tab@style#2}};%
    };%
  \end{tikzpicture}%
}
\endinput
%%
%% End of file `fancytabs.sty'.
```

**Comment by raphink** [comment]
OK, I'll have a look tomorrow.

**Comment by raphink** [comment]
OK, I'll have a look tomorrow.

**Comment by raphink** [comment]
That looks good to me. For future contributions, please open one PR per feature.

**Pull request merged**
